### PR TITLE
chore: add configuration for token issuer

### PR DESCRIPTION
**Pull request by furious-luke**
Added a configuration option to specify the issuer encoded into tokens. I found this was needed to support running in Docker with a suite of other services on the Docker network.

### CODE REVIEW

**Comment by jagregory** [comment]
Hey @furious-luke, I completely missed this PR somehow. Thanks for the contribution.

If you have a moment, could you elaborate why the issuer change was needed? I ask because I'm running it in docker and haven't had any issues. Mostly just for my curiosity.

Thanks also for the additional targets. I'll get this PR reviewed soon.

**Comment by furious-luke** [comment]
Hey @jagregory! The setup works perfectly well on `localhost` so long as you want to access the Cognito service from outside Docker (i.e. on your host machine). However, I was running the service from `docker-compose`, and my Cognito service was located within the Docker network at a hostname of `cognito`. So, any requests for authentication were rejected because they weren't asking `localhost` for authentication. The configuration option allows me to specify the hostname of the Cognito server.

Hope that makes sense!

**Comment by kadyrleev** [comment]
A good one. Thanks a lot. 
Also adding admin actions targets is very useful.

**Comment by jagregory** [comment]
Thanks @furious-luke that does make sense. I'm doing host to container stuff so it makes sense I haven't had any issue. I'll get this merged asap and a new release out. Cheers

**Comment by jagregory** [comment]
I'll need a little bit longer on this. I noticed your comment @furious-luke:

```ts
// TODO: Why was this here?
// Username: uuid.v4(),
Username: body.Username,
```

and that's made me realise I've used the Username and Sub interchangeably, which is incorrect. The Username is user-specified, and the Sub is the autogenerated UUID. I'm going to need to go through and update anywhere that uses the Username as the Sub, otherwise existing databases won't work correctly.

**Pull request merged**
